import pandas as pd
import numpy as np
from imblearn.over_sampling import ADASYN
from sklearn.preprocessing import LabelEncoder

class ADASYNBalancer:
    def __init__(self, target_col='attack_cat', random_state=42):
        self.target_col = target_col
        self.random_state = random_state

    def balance_dataset(self, df):
        """
        Balances minority classes in tabular dataset using ADASYN.
        Handles categorical label encoding, imputation, and oversampling.
        """
        df_balanced = df.copy()
        
        # Clean infinite values and NaNs prior to ADASYN
        df_balanced = df_balanced.replace([np.inf, -np.inf], np.nan).fillna(0)
        
        y = df_balanced[self.target_col].astype(str)
        X = df_balanced.drop(columns=[self.target_col])

        # ADASYN requires numeric feature inputs
        temp_encoders = {}
        X_numeric = pd.DataFrame()
        for col in X.columns:
            if X[col].dtype == 'object':
                le = LabelEncoder()
                X_numeric[col] = le.fit_transform(X[col].astype(str))
                temp_encoders[col] = le
            else:
                X_numeric[col] = pd.to_numeric(X[col], errors='coerce').fillna(0)

        # Check minority classes that have too few samples for default n_neighbors=5
        class_counts = y.value_counts()
        min_samples = class_counts.min()
        
        # Adaptive neighbor adjustment if rare class has < 6 samples
        n_neighbors = min(5, max(1, min_samples - 1))
        
        print(f"Applying ADASYN oversampling (n_neighbors={n_neighbors})...")
        try:
            adasyn = ADASYN(sampling_strategy='auto', n_neighbors=n_neighbors, random_state=self.random_state)
            X_res, y_res = adasyn.fit_resample(X_numeric, y)
        except Exception as e:
            print(f"ADASYN warning: {e}. Falling back to n_neighbors=1.")
            adasyn = ADASYN(sampling_strategy='auto', n_neighbors=1, random_state=self.random_state)
            X_res, y_res = adasyn.fit_resample(X_numeric, y)

        # Decode string columns back for consistency with downstream preprocessors
        X_res_df = pd.DataFrame(X_res, columns=X.columns)
        for col, le in temp_encoders.items():
            # Round nearest integer labels generated by ADASYN interpolation
            rounded_vals = np.clip(np.round(X_res_df[col].values).astype(int), 0, len(le.classes_) - 1)
            X_res_df[col] = le.inverse_transform(rounded_vals)

        X_res_df[self.target_col] = y_res.values
        print("Final balanced distribution with ADASYN:")
        print(X_res_df[self.target_col].value_counts())
        
        return X_res_df